/*var myApp=angular.module("myApp",['ngRoute']);
*/
var myApp=angular.module("myApp",['ngRoute',,'ngCookies']);

myApp.config(function($routeProvider)
{
	$routeProvider
	.when("/",{
		templateUrl:"home.html"
	})
	.when("/contact",{
		templateUrl:"contactus.html"
	})
	.when("/login",{
		templateUrl:"user/Login.html"
	})
	.when("/register",{
		templateUrl:"user/Register.html"
	})
	.when("/blog",{
		templateUrl:"Blog.html"
	})
	.when("/forum",{
		templateUrl:"Forum.html",
	})
	.when("/job",{
		templateUrl:"Job.html"
	})
	.when("/UserHome",{
		templateUrl:"user/UserHome.html"
	})
	.when("/logout",{
		templateUrl:"user/LogOut.html"
	})
	.when("/about",{
		templateUrl:"aboutus.html"
	})
	.when("/addBlog",{
		templateUrl:"blog/AddBlog.html"
	})
	.when("/viewProfile",{
		templateUrl:"user/ViewProfile.html"
	})
	.when("/updateProfile",{
		templateUrl:"user/UploadProfileForm.html"
	})
	.when("/uploadProfilePicture",{
		templateUrl:"user/UploadProfilePicture.html"
	})
	.when("/viewAllBlogs",{
		templateUrl:"blog/ViewAllBlogs.html"
	})
	
	.when("/updateBlogForm",{
		templateUrl:"blog/UpdateBlogForm.html"
	})
	.when("/addForum",{
		templateUrl:"forum/AddForum.html"
	})
	.when("/viewAllForums",{
		templateUrl:"forum/ViewAllForums.html"
	})
	.when("/updateForumForm",{
		templateUrl:"forum/UpdateForumForm.html"
	})
	.when("/startChat",{
		templateUrl:"chat/Chat.html"
	})
	.when("/viewSuggestedFriends",{
		templateUrl:"friend/ViewSuggestedFriends.html"
	})
	.when("/showPendingRequests",{
		templateUrl:"friend/ShowPendingRequests.html"
	})
	.when("/showAllFriends",{
		templateUrl:"friend/ShowAllFriends.html"
	})
	.when("/adminHome",{
		templateUrl:"admin/AdminHome.html"
	})
	.when("/listAllApprovedBlogs",{
		templateUrl:"blog/ListAllApprovedBlogs.html"
	})
	.when("/viewPendingBlogs",{
		templateUrl:"blog/ViewPendingBlogs.html"
	})
	.when("/ViewBlog",{
		templateUrl:"blog/ViewBlog.html"
	})
	.when("/AddCommentForm",{
		templateUrl:"blog/AddCommentForm.html"
	})
	.when("/addJobForm",{
		templateUrl:"job/AddJob.html"
	})
	.when("/viewAllJobs",{
		templateUrl:"job/ViewAllJobs.html"
	})
	.when("/viewAllAppliedJobs",{
		templateUrl:"job/ViewAllAppliedJobs.html"
	})
	.when("/ViewAllComments",{
		templateUrl:"blog/ViewAllComments.html"
	})
});
myApp.run(function($rootScope,$cookieStore)
		{
			console.log('I am in run function');
			console.log($rootScope.currentUser);
			
				if($rootScope.currentUser==undefined)
				{
				$rootScope.currentUser=$cookieStore.get('userDetails');
				$rootScope.currentBlog=$cookieStore.get('blogDetails');
				$rootScope.currentForum=$cookieStore.get('forumDetails');
				}
				else
				{
				console.log($rootScope.currentUser.userName);
				console.log($rootScope.currentUser.role);
				}
		});
